global using System.Collections.Generic;
global using System;
global using System.IO;
global using System.Threading.Tasks;
global using System.Text;
global using System.Collections;
global using System.Linq;
global using SunamoDebugIO._sunamo.SunamoExceptions;
global using System.Diagnostics;
global using TextCopy;
global using SunamoDebugIO._sunamo;
global using System.Reflection;
global using System.Net;
global using SunamoDebugIO._sunamo.SunamoValues;
global using System.Diagnostics.CodeAnalysis;
global using SunamoDebugIO;
global using System.Threading;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
